### PR TITLE
Add DIY intake export & create model to store these extracts

### PR DESCRIPTION
**Pull request by alaroia-cfa**
This pull request does very little, and since in the Pivotal Tracker story <https://www.pivotaltracker.com/story/show/173933108> we don't need a web UI for showing these, I think this is enough to get going.

Eager for feedback/review.

### CODE REVIEW

**Comment by bengolder** [comment]
This is fine as an incremental commit, but the end goal would be for this to produce a CSV that shows up in `AnonymizedIntakeCsvExtractsController` which should perhaps just be `AnonymizedCsvExtractsController`.

**Comment by alaroia-cfa** [comment]
@bengolder I'll push this, but I think I'm confused about the requirements. I think the story says all we need do is pull one CSV and get it to the right person, so I don't know that we really need UI if we can accomplish it from `rails c`.

**Comment by alaroia-cfa** [comment]
And @bengolder thanks for the review!

**Comment by alaroia-cfa** [comment]
@bengolder Oh... maybe you didn't strictly approve it as a review.  Hmm. Oops. Well, I'll chat with you elsewhere then.

**Pull request merged**
