### PR TITLE
Add state to the client list table [#175706866]

### PR DESCRIPTION
**Pull request by sartan**
image

### CODE REVIEW

**Comment by sniemeyer13** [comment]
In doing this story, we noticed that the "State" is tied to the intake, rather than the tax return. This could be slightly misleading because tax returns in different years could be tied to different States. (For example, if someone worked/lived in Texas in 2017 and then moved to Alabama in 2019, we currently only tie them to one of those States). 

In the UI for the client list page, we decided to tie the State column to the client, rather than to each tax return because this is the most accurate representation of the data. 

If we wanted to tie each tax year to a different State, we would have to change the intake flow to account for this information.

**Comment by bytheway875** [comment]
@sartan @sniemeyer13 The other thing here is that there are two fields on the intake: state_of_residence and then "state" which I think is the state filled out as part of the _mailing_ address. So state_of_residence is probably more accurate to the tax return _but_ im not sure if we require that people fill out state of residence on the intake... I looked on prod and we only maintain state of residence info for ~20 of the last 100 intakes

**Comment by sartan** [comment]
@bytheway875 Good call! We'll switch it from `state` to `state_of_residence`.

Also, we discussed having state tied to a given tax return year with Yvonne and she will create a separate story for that work.

**Review by embarnard — APPROVED** [review]
Great work! Nice to see the discussion with product in the story.

**Pull request merged**
