### PR TITLE
Add rack middleware to validate params before hitting the controller

### PR DESCRIPTION
**Pull request by embarnard**

### CODE REVIEW

**Review by bytheway875 — COMMENTED** [review]
This is super awesome work, @embarnard! I'm tagging @ddefigueiredo to see if he has any feedback on the specific html response codes we're using or any additional feedback 👯‍♂️

**Comment by bytheway875** [comment]
@embarnard I noticed there is still an issue with the fake controller thing :( -- are the specs passing locally?

**Comment by embarnard** [comment]
> @embarnard I noticed there is still an issue with the fake controller thing :( -- are the specs passing locally?

Yay thanks for tagging dimirtri! And yes they are passing locally :( unsure why they are failing here -- do you know where that example of the other fake controller in the app is?

**Comment by ddefigueiredo** [comment]
The 400 status code is exactly right here. I also like how you cleanly put the check inside `string_contains_invalid_character?` making it easy to modify this later.

**Pull request closed without merging**
