### PR TITLE
FYST Refactor: move some methods from IndividualReturn classes to parent class SubmissionBuilder::Document

### PR DESCRIPTION
**Pull request by jenny-heath**
## Link to pivotal/JIRA issue
- https://codeforamerica.atlassian.net/browse/FYST-139, kind of
## Is PM acceptance required?
- No - merge after code review approval
## What was done?
- as part of the experiment to add a new state, i found some good refactor ideas. some of them will go into stories and some of them i am just knocking out on my own because the effort to write a story doesn't seem worth it either for how small they are or for how complicated they are to explain
- this PR moves some methods into the `SubmissionBuilder::Document` class
- this one i actually feel somewhat unsure about because these methods are exact duplicates across the `IndividualReturn` classes for each state but they _only_ apply to those classes. other classes that inherit from `SubmissionBuilder::Document` either:
  - don't reference them at all, in the case of state-specific supplementary documents like `SubmissionBuilder::Ty2022::States::Ny::Documents::It215` or 
  - have them defined separately, in the case of federal submission builders like `SubmissionBuilder::Ty2021::Documents::Irs1040`
- since we will be keeping the federal submission building code for another year or so this feels a little more complicated to me. please share your thoughts!
## How to test?
- any issues should be caught by the individual return tests

### CODE REVIEW

**Review by mrotondo — COMMENTED** [review]
Would creating an intermediate class in the hierarchy called something like `StateFile::StateDocument < SubmissionBuilder::Document` which had these 5 methods on it, then making all the FYST documents inherit from that, feel better than moving them into the top-level document class where not all the subclasses will use them?

**Comment by mrotondo** [comment]
> Would creating an intermediate class in the hierarchy called something like `StateFile::StateDocument < SubmissionBuilder::Document` which had these 5 methods on it, then making all the FYST documents inherit from that, feel better than moving them into the top-level document class where not all the subclasses will use them?

Re-reading your comment, this seems like it would have the same conceptual issues since there are other state file documents that don't use these methods. Maybe a mixin that the state individual returns include?

I'm failing to find where/how these methods are defined separately for the federal submission builders - can you point me at those definitions?

**Comment by jenny-heath** [comment]
@mrotondo re: separately defined methods for federal, i guess i should have said _some_ of them are separately defined in _some_ places and as it turns out i didn't look that closely because the first example i could find for you is on an intermediate class (similar to what you suggested!) not on the child class: https://github.com/codeforamerica/vita-min/blob/main/app/lib/submission_builder/shared/return1040.rb#L25-L27

**Comment by mrotondo** [comment]
> @mrotondo re: separately defined methods for federal, i guess i should have said _some_ of them are separately defined in _some_ places and as it turns out i didn't look that closely because the first example i could find for you is on an intermediate class (similar to what you suggested!) not on the child class: https://github.com/codeforamerica/vita-min/blob/main/app/lib/submission_builder/shared/return1040.rb#L25-L27

That's helpful, thanks. I think that following this pattern with a new intermediate subclass of document that's only inherited by FYST state individual return documents, and which includes these methods, seems like it'd be good for this PR.

**Review by mrotondo — APPROVED** [review]
This looks good structurally, and I think the names are fine but we're about to talk about that in CGC!

**Pull request merged**
