### PR TITLE
Update honeycrisp from 0.9.6 to 0.10.4

### PR DESCRIPTION
**Pull request by coltborg**
# What does this PR do?

- Update Honeycrisp to the latest version ([from 0.9.6 to 0.10.4](https://github.com/codeforamerica/honeycrisp-gem/compare/v0.9.6...v0.10.4)).
  - The [migration guide](https://github.com/codeforamerica/honeycrisp-gem/blob/main/MIGRATING.md) mentions that since we are importing the manifest, no changes are needed:
    - > If you imported the manifest (ie as import 'cfa_styleguide_main' in application.scss), no changes are needed.
- Updated Honeycrisp override code in GYR that was using `is-hidden` to now use `is-hiding-content`, [which Honeycrisp now does](https://github.com/codeforamerica/honeycrisp-gem/pull/281).

# Testing

We tested this PR locally and with [Percy](https://percy.io/Code-for-America/vita-min) to check for any differences from [`main`](https://percy.io/Code-for-America/vita-min/builds/12606881/changed/711791099?browser=edge&browser_ids=19%2C20%2C21&subcategories=approved&viewLayout=overlay&viewMode=new&width=375&widths=375%2C1280) (percy calls this the baseline build) and this [pr branch](https://percy.io/Code-for-America/vita-min/builds/12625334/changed/712870418?browser=edge&browser_ids=19%2C20%2C21&subcategories=approved&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280).

### CODE REVIEW

**Comment by coltborg** [comment]
Types of visual changes in Percy:
* 2x content missing (reveal)
  * optional consent page
  * hub user edit
  * possibly due to render timing & javascript. might be a bug that is not branch-specific (assumed)
  * actual difference in the code?
* 44x small horizontal text rendering difference in MS Edge
  * we could not see any significant human perceptible difference, so we concluded that these are false positives. We do not understand the cause.
  * seems to be isolated to MS Edge, so it's unlikely it has anything to do with our code.

**Comment by coltborg** [comment]
- [ ] Investigate why reveals are being removed from the page
  - [ ] hub user edit page
  - [ ] questions/optional-consent page
- [ ] If issue is in GYR, fix the issue in this PR

**Comment by coltborg** [comment]
We noticed changes that we think are false positives in MS Edge and so we approved those. You can see the Percy run [here](https://percy.io/Code-for-America/vita-min/builds/12625334/changed/712870418?browser=edge&browser_ids=19%2C20%2C21&subcategories=approved&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280) for more details.

**Review by alaroia-cfa — COMMENTED** [review]
> 2x content missing (reveal)

@coltborg are these now fixed due to the change from `is-hidden` to `is-hiding-content`? If so, I'll click "Approve"!

Generally, this is stellar. Thanks for working on it!

**Comment by coltborg** [comment]
@alaroia-cfa, correct. Reveals have been fixed!

**Review by alaroia-cfa — APPROVED** [review]
:D

**Pull request merged**
