### PR TITLE
Add IRS business name type validator

### PR DESCRIPTION
**Pull request by jenny-heath**
Use Rails validator for length

Co-authored-by: Asheesh Laroia <alaroia@codeforamerica.org>

### CODE REVIEW

**Comment by jenny-heath** [comment]
closing to re-deploy heroku

**Comment by jenny-heath** [comment]
trying again? gonna wait this time

**Review by alaroia-cfa — APPROVED** [review]
lgtm yay

**Review by alaroia-cfa — COMMENTED** [review]
got a review from Jenny via Tuple a moment ago

**Pull request merged**
