### PR TITLE
Economic Impact Payment and Child Tax Credit Calculators

### PR DESCRIPTION
**Pull request by miketlawrence**
We need to be able to calculate expected Economic Impact Payment (EIP), and Child Tax Credits values.

## Formula
**EIP1**
$1,200 x (# of eligible individuals) + $500 x (# of eligible dependents)

**EIP2**
$600 x (# of eligible individuals) + $600 x (# of eligible dependents)

**EIP2**
$1,400 x (# of eligible individuals) + $1,400 x (# of eligible dependents)

**CTC**
Dependents under 6 yrs. $300 per month / $3600 total
Dependents aged 6-17 yrs. $250 per month / $3000 total

NOTE:
The number of filers, and eligible dependents will be determined with a separate class.

### CODE REVIEW

**Comment by bytheway875** [comment]
This is great!! Can I ask for one change? Can you move all of these files into app/lib instead of app/services?

**Review by bytheway875 — APPROVED** [review]
Woo hoo! Thanks @miketlawrence

**Comment by bytheway875** [comment]
(P.S. I'm going to merge this tomorrow because I think that the forked branches don't get picked up by CI automatically, it looks like) @miketlawrence

**Comment by miketlawrence** [comment]
> (P.S. I'm going to merge this tomorrow because I think that the forked branches don't get picked up by CI automatically, it looks like) @miketlawrence

Sounds good 🎉

**Pull request merged**
