### PR TITLE
State file: update 2023 federal schema to version 5.0

### PR DESCRIPTION
**Pull request by jenny-heath**

### CODE REVIEW

**Review by bengolder — APPROVED** [review]
Thanks!

**Comment by jenny-heath** [comment]
@bengolder this wasn't quite ready when you approved it! (still had some failing tests and hadn't uploaded the new schema to S3). i hope it's ready now, please give it another look if you have time!

**Review by bengolder — APPROVED** [review]
Approved again!

**Comment by bengolder** [comment]
@jenny-heath I noticed that the fed return sample schemas were updated. Should we be concerned about existing intakes on demo that used the old schema? Would it break any of those to merge this? Is direct file now sending us XML that matches the new schema?

**Comment by bengolder** [comment]
In regards to my previous questions:
> Should we be concerned about existing intakes on demo that used the old schema? Would it break any of those to merge this? Is direct file now sending us XML that matches the new schema?

@embarnard answered in Slack that we should not be concerned about breaking existing intakes that were based on the old schema. This is likely safe to merge. It remains unclear if direct file is yet sending us XML that matches the new schema.

Merging

**Pull request merged**
